GET http://192.168.31.249:3002/widgets/iub54i6bibu64/shome

###

GET http://192.168.31.249:3002/tabs/divyanshg21/shome

###

POST http://192.168.31.249:3002/newWidget/iub54i6bibu64/shome
Content-Type: application/json

{
        "name": "Demo5",
        "feed": "Web_Sensor",
        "type": "chart",
        "datasets": [{
            "label": "Temperature4",
            "data": "",
            "backgroundColor": "transparent",
            "borderColor": "green",
            "borderWidth": 1
        }],
        "config": {
            "labels": "",
            "type": "bar",
            "prevTime": "ret4",
            "device": "qwerty12",
            "tab": "z1lPCMArNK"
        }
}
###

POST http://192.168.31.249:3002/newTab/divyanshg21/shome/Drone2

###
POST http://192.168.31.249:3002/newDevice/divyanshg21/fckdevice/somedid/test

###
GET http://192.168.31.249:3002/devices/iub54i6bibu64


###
GET http://192.168.31.249:3002/deviceState/GZBIC1oqQN

###
POST http://192.168.31.249:6543/authority/verify/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6ImRpdiJ9LCJpYXQiOjE1ODg4NzYyMzF9.Jg0PelxAMUYklR27_l4j9CXzrSaQ6M-upor0Uy4ccIU