GET http://192.168.31.72:3002/widgets/userHII/app

###

GET http://192.168.31.72:3002/tabs/userHII/app

###

GET http://192.168.31.249:3002/newWidget/divyanshg21/shome
Content-Type: 'application/json'

{
    name: "divy"
}